change syslog,ssh,ntp command
aicers/roxy pull request #263
Opened 2024-01-22 01:12 UTC by syncpark

Change syslog, ssh, ntp control command

2024-03-20 16:55 UTC, msk requested changes

2024-03-20 16:55 UTC, msk commented on clippy.toml
> +doc-valid-idents = [ "REview", "run_roxy" ]
Rather than including `run_roxy` here, we should use backticks as in `` `run_roxy` `` in documentation.

2024-03-21 00:46 UTC, syncpark commented on clippy.toml
> +doc-valid-idents = [ "REview", "run_roxy" ]
done

2024-03-21 18:36 UTC, msk approved these changes

2024-03-22 06:29 UTC, merged