Separate user's and root's commands
aicers/roxy pull request #67
Opened 2022-09-15 12:57 UTC by sehkone

The functions listed in `lib.rs` are not covering all of required commands. The rest will be added.

2022-09-15 22:19 UTC, msk requested changes

2022-09-15 22:19 UTC, msk commented on src/common.rs
> +    #[allow(dead_code)]
Any plan to use this?

2022-09-15 22:19 UTC, msk commented on src/common.rs
> +    pub fn debug<T>(&self)
Isn't it better to `impl Debug`?

2022-09-15 22:19 UTC, msk commented on src/common.rs
> +    #[allow(dead_code)]
Please add a comment explaining why this shouldn't be deleted. `#[allow(dead_code)]` must be treated in the same way as commented-out codes.

2022-09-15 22:19 UTC, msk commented on src/common.rs
> +/// Run linux command and return it's output
A rustdoc comment starts with "Runs ..." rather than "Run ...".

2022-09-15 23:36 UTC, sehkone commented on src/common.rs
> +    #[allow(dead_code)]
Corrected

2022-09-15 23:37 UTC, sehkone commented on src/common.rs
> +    pub fn debug<T>(&self)
Erased because it is not used

2022-09-15 23:37 UTC, sehkone commented on src/common.rs
> +    #[allow(dead_code)]
Corrected

2022-09-15 23:39 UTC, sehkone commented on src/common.rs
> +/// Run linux command and return it's output
I corrected this but I didn't check others which may exist. Whenever I find similar ones, I will correct them.

2022-09-16 00:38 UTC, msk requested changes

2022-09-16 00:38 UTC, msk commented on src/root.rs
> +/// Run linux command
Run → Runs

2022-09-16 00:38 UTC, msk commented on src/root/hwinfo.rs
> +/// Set OS or Product version. Refer /etc/version
Set → Sets

2022-09-16 02:06 UTC, sehkone commented on src/root.rs
> +/// Run linux command
There are many mistakes like this here and there. This should be corrected properly by the author. I will post an issue.

2022-09-16 04:05 UTC, sehkone commented on src/root.rs
> +/// Run linux command
I post an issue #69

2022-09-16 16:26 UTC, msk approved these changes

2022-09-16 16:28 UTC, merged